import { StyleSheet } from 'react-native';

export const authSheetStyles = StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  keyboardWrap: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: 'rgba(39, 22, 55, 0.72)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 14,
    paddingHorizontal: 38,
    paddingBottom: 28,
    minHeight: 580,
    maxHeight: '92%',
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#A47DFF',
    shadowOpacity: 0.22,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: -8 },
    elevation: 18,
    overflow: 'hidden',
  },
  blurLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(73, 38, 103, 0.32)',
  },
  contentShell: {
    flex: 1,
  },
  contentScroll: {
    paddingBottom: 18,
  },
  sheetBody: {
    gap: 16,
  },
  handle: {
    alignSelf: 'center',
    width: 82,
    height: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(72, 47, 91, 0.52)',
    marginBottom: 34,
  },
  title: {
    color: '#FBF7FF',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 26,
    textShadowColor: 'rgba(0,0,0,0.34)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 8,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.7)',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 20,
    fontSize: 14,
    lineHeight: 19,
  },
  content: {
    paddingBottom: 10,
  },
  expandedProviderCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(121, 116, 116, 0.29)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  providerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  providerIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  providerIconGoogle: {
    color: '#4285F4',
  },
  providerIconApple: {
    fontSize: 25,
  },
  providerHeaderLabel: {
    color: '#F6EEFF',
    fontSize: 12,
    fontWeight: '700',
  },
  providerGroup: {
    gap: 16,
    marginBottom: 18,
  },
  providerCard: {
    minHeight: 60,
    width: '100%',
    borderRadius: 12,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  providerCardCollapsed: {
    backgroundColor: 'rgba(40, 25, 52, 0.76)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 2,
  },
  providerCardExpanded: {
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    backgroundColor: 'rgba(61, 37, 75, 0.74)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    width: '100%',
  },
  providerLabel: {
    color: '#F6EEFF',
    fontSize: 19,
    fontWeight: '700',
    flex: 1,
    marginLeft: 14,
  },
  providerArrow: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 32,
    lineHeight: 32,
    marginTop: -2,
  },
  fieldGroup: {
    gap: 9,
    marginBottom: 4,
  },
  fieldLabel: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: -2,
  },
  loginHint: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 12,
  },
  input: {
    minHeight: 40,
    borderRadius: 10,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(35, 23, 45, 0.86)',
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(207, 169, 255, 0.16)',
  },
  submitButton: {
    minHeight: 48,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    width: '68%',
    backgroundColor: 'rgba(242, 240, 246, 0.78)',
    marginTop: 10,
    marginBottom: -2,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  submitLabel: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  closeButton: {
    minHeight: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(58, 39, 75, 0.8)',
    marginBottom: 10,
  },
  closeLabel: {
    color: '#E8DDF5',
    fontSize: 13,
    fontWeight: '600',
  },
  switchButton: {
    alignItems: 'center',
    paddingTop: 0,
  },
  switchLabel: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 12,
    fontWeight: '500',
    textAlign: 'center',
  },
  switchLabelStrong: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  pressedState: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
});
