import { StyleSheet } from 'react-native';

export const chatStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#111111',
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 0,
    left: -132,
    width: 470,
    height: 470,
    opacity: 0.78,
  },
  headerRow: {
    minHeight: 100,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 40,
    paddingBottom: 14,
    backgroundColor: 'rgba(38, 34, 43, 0.82)',
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -4,
  },
  backButtonText: {
    color: '#F4EEF9',
    fontSize: 36,
    lineHeight: 36,
    fontWeight: '300',
  },
  headerAvatarImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#A954F7',
  },
  headerTextWrap: {
    flex: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 18,
  },
  headerTitle: {
    color: '#F4EEF9',
    fontSize: 13,
    fontWeight: '800',
  },
  headerDot: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 9,
    lineHeight: 12,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.54)',
    fontSize: 9,
    marginTop: 1,
    fontWeight: '500',
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22EC7C',
  },
  onlineText: {
    color: '#22EC7C',
    fontSize: 8,
    fontWeight: '800',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(169, 113, 215, 0.55)',
  },
  body: {
    flex: 1,
  },
  messagesScroll: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingTop: 30,
    paddingBottom: 18,
  },
  datePill: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.07)',
    marginBottom: 22,
  },
  dateText: {
    color: '#908794',
    fontSize: 8,
    fontWeight: '700',
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 22,
    gap: 8,
  },
  assistantRow: {
    justifyContent: 'flex-start',
    paddingRight: 28,
  },
  userRow: {
    justifyContent: 'flex-end',
    paddingLeft: 46,
  },
  messageAvatarImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#A954F7',
  },
  messageStack: {
    maxWidth: '82%',
    alignItems: 'flex-start',
  },
  userMessageStack: {
    alignItems: 'flex-end',
  },
  userBadge: {
    width: 28,
    height: 28,
    borderRadius: 10,
    backgroundColor: '#7C2EC4',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  userBadgeText: {
    color: '#F8F1FF',
    fontSize: 13,
    fontWeight: '800',
  },
  messageBubble: {
    borderRadius: 8,
    paddingHorizontal: 13,
    paddingVertical: 12,
    borderWidth: 1,
  },
  assistantBubble: {
    backgroundColor: 'rgba(55, 47, 63, 0.94)',
    borderColor: '#7E6497',
  },
  userBubble: {
    backgroundColor: '#3A2E45',
    borderColor: '#7E6497',
  },
  messageText: {
    color: '#F1ECF4',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  userText: {
    color: '#FFFFFF',
  },
  timestamp: {
    color: 'rgba(205, 197, 211, 0.48)',
    fontSize: 8,
    fontWeight: '500',
    marginTop: 7,
    marginLeft: 2,
  },
  userTimestamp: {
    marginRight: 2,
  },
  budgetCard: {
    width: 235,
    marginTop: 10,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingTop: 17,
    paddingBottom: 15,
    backgroundColor: 'rgba(45, 39, 51, 0.96)',
    borderWidth: 1,
    borderColor: '#7E6497',
  },
  budgetTitle: {
    color: 'rgba(236, 228, 241, 0.68)',
    fontSize: 10,
    fontWeight: '800',
    marginBottom: 16,
  },
  budgetLine: {
    minHeight: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  budgetLabel: {
    color: 'rgba(236, 228, 241, 0.76)',
    fontSize: 9,
    fontWeight: '700',
    flex: 1,
  },
  budgetValue: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
    textAlign: 'right',
    flexShrink: 0,
  },
  progressTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: '#8E7896',
    marginTop: 14,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#D36CE3',
  },
  budgetCaption: {
    color: 'rgba(236, 228, 241, 0.58)',
    fontSize: 8,
    fontWeight: '600',
    marginTop: 8,
  },
  composer: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(169, 113, 215, 0.45)',
    backgroundColor: '#111111',
  },
  quickPromptRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  quickPromptButton: {
    flex: 1,
    minHeight: 31,
    paddingHorizontal: 10,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(42, 39, 46, 0.95)',
    borderWidth: 1,
    borderColor: '#7E6497',
  },
  quickPromptIcon: {
    color: '#B95EFF',
    fontSize: 16,
    lineHeight: 17,
    fontWeight: '800',
  },
  quickPromptText: {
    color: '#BDB3C4',
    fontSize: 10,
    fontWeight: '700',
  },
  inputShell: {
    minHeight: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(42, 39, 46, 0.96)',
    borderWidth: 1,
    borderColor: '#6F5A7C',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 13,
    paddingRight: 5,
    gap: 8,
  },
  inputIcon: {
    color: 'rgba(210, 200, 217, 0.36)',
    fontSize: 19,
    lineHeight: 20,
    fontWeight: '600',
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 108,
    color: '#FFFFFF',
    paddingVertical: 11,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  micIcon: {
    color: 'rgba(210, 200, 217, 0.42)',
    fontSize: 18,
    lineHeight: 19,
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonText: {
    color: 'rgba(210, 200, 217, 0.58)',
    fontSize: 22,
    lineHeight: 23,
    fontWeight: '700',
  },
});
