import { StyleSheet } from 'react-native';

export const chatStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0A090B',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
  },
  topGlow: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: 'rgba(147, 76, 255, 0.18)',
    top: 24,
    right: -84,
  },
  bottomGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(120, 60, 190, 0.14)',
    bottom: -48,
    left: -88,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 52,
    left: -120,
    width: 460,
    height: 460,
    opacity: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 4,
    paddingBottom: 12,
  },
  backButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: '#F1EBF7',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '400',
  },
  headerAvatarImage: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  headerTextWrap: {
    flex: 1,
  },
  headerTitle: {
    color: '#F4EEF9',
    fontSize: 13,
    fontWeight: '700',
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.44)',
    fontSize: 9,
    marginTop: 1,
    fontWeight: '500',
  },
  onlinePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#36E57A',
  },
  onlineText: {
    color: '#D9D0DB',
    fontSize: 9,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  body: {
    flex: 1,
    paddingTop: 10,
  },
  messagesScroll: {
    flex: 1,
  },
  messagesContent: {
    paddingBottom: 14,
  },
  datePill: {
    alignSelf: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.07)',
    marginBottom: 16,
  },
  dateText: {
    color: '#B9B0C0',
    fontSize: 9,
    fontWeight: '600',
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 16,
    gap: 8,
  },
  assistantRow: {
    justifyContent: 'flex-start',
  },
  userRow: {
    justifyContent: 'flex-end',
  },
  messageAvatarImage: {
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  userBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#7840C8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userBadgeText: {
    color: '#F8F1FF',
    fontSize: 10,
    fontWeight: '800',
  },
  messageBubble: {
    maxWidth: '72%',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
  },
  assistantBubble: {
    backgroundColor: 'rgba(55, 47, 63, 0.92)',
    borderColor: 'rgba(163, 137, 198, 0.42)',
  },
  userBubble: {
    backgroundColor: '#43344F',
    borderColor: 'rgba(198, 153, 255, 0.36)',
  },
  messageText: {
    color: '#F0EBF5',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
  },
  userText: {
    color: '#FFFFFF',
  },
  quickPromptRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  quickPromptButton: {
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  quickPromptText: {
    color: '#D9D0DB',
    fontSize: 10,
    fontWeight: '600',
  },
  inputShell: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    paddingTop: 10,
  },
  input: {
    flex: 1,
    minHeight: 54,
    maxHeight: 120,
    borderRadius: 18,
    backgroundColor: 'rgba(42, 39, 46, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    color: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    lineHeight: 18,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#8E2FF2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
});