import { StyleSheet } from 'react-native';

export const historyStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#080707',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    minHeight: '100%',
  },
  topGlow: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 230,
    backgroundColor: 'rgba(147, 76, 255, 0.18)',
    top: 42,
    right: -84,
  },
  bottomGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(120, 60, 190, 0.16)',
    bottom: 12,
    left: -80,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 52,
    left: -120,
    width: 460,
    height: 460,
    opacity: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIcon: {
    color: '#F4EEF9',
    fontSize: 30,
    lineHeight: 30,
    fontWeight: '400',
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    color: '#F4EEF9',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  headerSubtitle: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 9,
    marginTop: 1,
    fontWeight: '500',
  },
  avatarMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#EBEBEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    color: '#2B2430',
    fontSize: 13,
    fontWeight: '700',
  },
  summaryCard: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    marginBottom: 14,
    borderRadius: 10,
  },
  summaryCardContent: {
    position: 'relative',
    zIndex: 2,
  },
  summaryTitle: {
    color: 'rgba(237, 226, 248, 0.78)',
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  summaryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  summaryItem: {
    flex: 1,
    alignItems: 'center',
  },
  summaryValue: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 4,
  },
  summaryNegative: {
    color: '#FF8E8A',
  },
  summaryLabel: {
    color: '#C7B8DD',
    fontSize: 9,
    fontWeight: '600',
  },
  sectionBlock: {
    marginBottom: 12,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  sectionRule: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.24)',
  },
  sectionTitle: {
    color: '#F5EEFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  activityCard: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
  },
  activityCardContent: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activityLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingRight: 10,
  },
  activityAvatarWrap: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#483252',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityAvatarText: {
    color: '#9F89FF',
    fontSize: 10,
    fontWeight: '800',
  },
  activityDot: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 7,
    height: 7,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#111',
  },
  activityDotPositive: {
    backgroundColor: '#3BE25F',
  },
  activityDotNegative: {
    backgroundColor: '#FF5959',
  },
  activityTextWrap: {
    flex: 1,
  },
  activityNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  activityName: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
    maxWidth: '62%',
  },
  tagPill: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(92, 123, 255, 0.26)',
    borderWidth: 1,
    borderColor: 'rgba(92, 123, 255, 0.42)',
  },
  tagPillText: {
    color: '#BFD0FF',
    fontSize: 8,
    fontWeight: '700',
  },
  activityMeta: {
    color: 'rgba(255,255,255,0.56)',
    fontSize: 9,
    fontWeight: '500',
  },
  activityRight: {
    alignItems: 'flex-end',
    gap: 2,
  },
  activityAmount: {
    fontSize: 12,
    fontWeight: '800',
  },
  activityAmountPositive: {
    color: '#48D464',
  },
  activityAmountNegative: {
    color: '#FF5C5C',
  },
  activityFiat: {
    color: 'rgba(255,255,255,0.52)',
    fontSize: 8,
    fontWeight: '600',
  },
  statusPill: {
    marginTop: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
  },
  statusConfirmed: {
    borderColor: '#31B84A',
    backgroundColor: 'rgba(49, 184, 74, 0.12)',
  },
  statusPending: {
    borderColor: '#D8A83D',
    backgroundColor: 'rgba(216, 168, 61, 0.12)',
  },
  statusPillText: {
    color: '#EDE7F6',
    fontSize: 8,
    fontWeight: '700',
  },
  bottomNav: {
    height: 60,
    borderRadius: 16,
    backgroundColor: '#2C262E',
    borderWidth: 1,
    borderColor: '#675C6A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    flex: 1,
  },
  tabLabel: {
    color: '#D7D1DA',
    fontSize: 9,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#D98ED5',
  },
});
