import { StyleSheet } from 'react-native';

export const landingStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#090909',
  },
  frame: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 18,
    overflow: 'hidden',
  },
  backgroundGlow: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 320,
    backgroundColor: 'rgba(168, 92, 255, 0.16)',
    bottom: -100,
    right: -110,
    shadowColor: '#A55BFF',
    shadowOpacity: 0.75,
    shadowRadius: 58,
    shadowOffset: { width: 0, height: 0 },
  },
  backgroundGlowSecondary: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: 'rgba(233, 173, 255, 0.07)',
    top: 96,
    left: -72,
    shadowColor: '#F2C2FF',
    shadowOpacity: 0.42,
    shadowRadius: 48,
    shadowOffset: { width: 0, height: 0 },
  },
  header: {
    alignItems: 'center',
    width: '100%',
    paddingTop: 6,
  },
  headerLogo: {
    width: 132,
    height: 36,
  },
  heroArea: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 360,
  },
  brandMarkWrap: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandMarkGlow: {
    position: 'absolute',
    inset: 0,
    borderRadius: 999,
    backgroundColor: 'rgba(168, 92, 255, 0.12)',
    shadowColor: '#A55BFF',
    shadowOpacity: 0.55,
    shadowRadius: 38,
    shadowOffset: { width: 0, height: 0 },
  },
  brandMarkGlass: {
    width: '78%',
    height: '78%',
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  brandLogoImage: {
    width: '84%',
    height: '84%',
  },
  ringLarge: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.38)',
    transform: [{ scaleX: 0.95 }, { scaleY: 0.82 }],
  },
  ringMedium: {
    position: 'absolute',
    width: '82%',
    height: '82%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    transform: [{ scaleX: 0.95 }, { scaleY: 0.82 }],
  },
  orbitLeft: {
    position: 'absolute',
    width: '28%',
    height: '28%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    left: -10,
    top: '34%',
    transform: [{ rotate: '-18deg' }],
  },
  orbitRight: {
    position: 'absolute',
    width: '28%',
    height: '28%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    right: -10,
    top: '16%',
    transform: [{ rotate: '18deg' }],
  },
  orbitBottom: {
    position: 'absolute',
    width: '36%',
    height: '36%',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    left: '6%',
    bottom: '6%',
    transform: [{ rotate: '22deg' }],
  },
  floatingSquare: {
    position: 'absolute',
    borderRadius: 12,
    backgroundColor: '#C77DF1',
    opacity: 0.4,
  },
  floatingSquareTopLeft: {
    top: 120,
    left: 30,
    backgroundColor: '#E3A1D5',
    transform: [{ rotate: '-15deg' }],
  },
  floatingSquareTopRight: {
    top: 140,
    right: 40,
    backgroundColor: '#E3A1D5',
    transform: [{ rotate: '12deg' }],
  },
  floatingSquareBottomRight: {
    bottom: 180,
    right: 30,
    backgroundColor: '#9D48EE',
    transform: [{ rotate: '18deg' }],
  },
  floatingSquareLeft: {
    top: '28%',
    left: '18%',
    backgroundColor: '#E3A1D5',
  },
  floatingSquareRight: {
    top: '28%',
    right: '18%',
    backgroundColor: '#E3A1D5',
  },
  floatingSquareLower: {
    right: '18%',
    bottom: '26%',
    backgroundColor: '#9D48EE',
  },
  curvedLineLeft: {
    position: 'absolute',
    top: '35%',
    left: -20,
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    transform: [{ rotate: '-25deg' }],
  },
  curvedLineRight: {
    position: 'absolute',
    top: '40%',
    right: -30,
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    transform: [{ rotate: '20deg' }],
  },
  bottomRightGlow: {
    position: 'absolute',
    bottom: 100,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: 'rgba(147, 76, 255, 0.15)',
    shadowColor: '#934CFF',
    shadowOpacity: 0.4,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: 0 },
  },
  logoCard: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
    backgroundColor: '#8E2DF0',
    shadowColor: '#4F0FD0',
    shadowOpacity: 0.52,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 52,
    left: -120,
    width: 460,
    height: 460,
    opacity: 1,
  },
  logoEarLeft: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#B780FF',
    opacity: 0.78,
    alignSelf: 'center',
    position: 'absolute',
    top: '35%',
    left: '33%',
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#5F23B8',
  },
  logoEyeRight: {
    position: 'absolute',
    top: '35%',
    right: '33%',
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#5F23B8',
  },
  logoNose: {
    position: 'absolute',
    top: '43%',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#5F23B8',
  },
  logoMuzzle: {
    position: 'absolute',
    bottom: '19%',
    width: '42%',
    height: '14%',
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  footer: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 4,
  },
  buttonStack: {
    width: '100%',
    alignItems: 'center',
    gap: 12,
  },
  buttonBase: {
    width: '72%',
    maxWidth: 240,
    minHeight: 28,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderWidth: 1,
  },
  buttonPrimary: {
    backgroundColor: 'rgba(205, 166, 230, 0.56)',
    borderColor: 'rgba(255,255,255,0.18)',
    shadowColor: '#B86EFF',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonSecondary: {
    backgroundColor: 'rgba(80, 80, 90, 0.56)',
    borderColor: 'rgba(255,255,255,0.18)',
    shadowColor: '#505050',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.92,
  },
  buttonLabel: {
    color: '#FFF8FF',
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  buttonLabelSecondary: {
    color: '#E7DFF7',
  },
  legalText: {
    marginTop: 12,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.48)',
    fontSize: 8,
    lineHeight: 11,
    maxWidth: 210,
  },
  legalLink: {
    color: 'rgba(255,255,255,0.82)',
    fontWeight: '600',
  },
});