import { StyleSheet } from 'react-native';

export const receiptStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#171717',
  },
  content: {
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 28,
    alignItems: 'center',
  },
  receiptCard: {
    width: '100%',
    maxWidth: 420,
    minHeight: 760,
    borderWidth: 2,
    borderColor: '#1FA0FF',
    backgroundColor: '#1A1A1A',
    paddingHorizontal: 26,
    paddingTop: 32,
    paddingBottom: 24,
  },
  successBadge: {
    width: 104,
    height: 104,
    borderRadius: 52,
    alignSelf: 'center',
    backgroundColor: '#1BAA49',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1BAA49',
    shadowOpacity: 0.55,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 8,
    marginBottom: 28,
  },
  successIcon: {
    color: '#FFFFFF',
    fontSize: 56,
    fontWeight: '900',
    lineHeight: 58,
  },
  statusTitle: {
    color: '#D0CBF4',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 24,
  },
  sectionLabelRow: {
    marginBottom: 8,
  },
  sectionLabel: {
    color: '#FFFFFF',
    fontSize: 11,
    letterSpacing: 0.8,
    fontWeight: '700',
  },
  recipientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  recipientAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FF7A00',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipientAvatarText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  recipientTextWrap: {
    flex: 1,
  },
  recipientName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  recipientSubtext: {
    color: 'rgba(255,255,255,0.62)',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
  },
  detailDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.12)',
    marginVertical: 10,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  detailLabel: {
    flex: 1,
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    fontWeight: '500',
  },
  detailValue: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  detailValuePrimary: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  detailValueGreen: {
    color: '#1DDB67',
    fontSize: 13,
    fontWeight: '800',
  },
  detailValueMuted: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  detailValuePurple: {
    color: '#C56BFF',
    fontSize: 12,
    fontWeight: '700',
  },
  detailValueMixed: {
    color: '#C56BFF',
    fontSize: 13,
    fontWeight: '700',
  },
  primaryAction: {
    minHeight: 58,
    borderRadius: 30,
    marginTop: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6E67C8',
    shadowColor: '#A9A0FF',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  primaryActionText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 18,
  },
  secondaryAction: {
    flex: 1,
    minHeight: 34,
    borderRadius: 18,
    backgroundColor: '#707070',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  footerNoteBox: {
    marginTop: 22,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(51, 184, 87, 0.45)',
    backgroundColor: 'rgba(20, 57, 28, 0.7)',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  footerNote: {
    color: '#69D97A',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 15,
  },
});