import { StyleSheet } from 'react-native';

export const remitStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#080707',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
    minHeight: '100%',
  },
  topGlow: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 230,
    backgroundColor: 'rgba(147, 76, 255, 0.18)',
    top: 42,
    right: -84,
  },
  bottomGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(120, 60, 190, 0.16)',
    bottom: 12,
    left: -80,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 48,
    left: -110,
    width: 440,
    height: 440,
    opacity: 1,
  },
  screenHeader: {
    color: 'rgba(244, 233, 255, 0.42)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
    marginLeft: 2,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIcon: {
    color: '#F4EEF9',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '400',
  },
  avatarMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#EBEBEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    color: '#2B2430',
    fontSize: 13,
    fontWeight: '700',
  },
  remitTitle: {
    color: 'rgba(244, 233, 255, 0.86)',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
    marginLeft: 4,
  },
  totalBalancePanel: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    minHeight: 74,
    borderRadius: 12,
  },
  totalBalancePanelContent: {
    position: 'relative',
    zIndex: 2,
  },
  totalBalanceLabel: {
    color: 'rgba(232, 222, 244, 0.52)',
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  totalBalanceValue: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  transferCard: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 16,
    marginBottom: 18,
    borderRadius: 12,
  },
  transferCardContent: {
    position: 'relative',
    zIndex: 2,
  },
  transferCardTitle: {
    color: 'rgba(228, 220, 240, 0.6)',
    fontSize: 10,
    fontWeight: '800',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  transferFieldLabel: {
    color: 'rgba(223, 214, 242, 0.62)',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: 6,
    letterSpacing: 0.25,
  },
  tokenSelect: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tokenSelectLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tokenSymbol: {
    color: '#F4F1F5',
    fontSize: 10,
    fontWeight: '800',
  },
  tokenBalance: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 8,
    marginTop: 1,
    fontWeight: '600',
  },
  dropdownChevron: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 20,
    lineHeight: 20,
    marginTop: -2,
  },
  assetPickerRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    marginBottom: 8,
  },
  assetChip: {
    minHeight: 18,
    minWidth: 34,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#68666B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetBadgeBlue: {
    backgroundColor: '#2087FF',
  },
  assetBadgeTeal: {
    backgroundColor: '#20C5C3',
  },
  assetBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  assetChipText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '800',
  },
  amountBlock: {
    marginBottom: 2,
  },
  amountInput: {
    minHeight: 38,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickAmountRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  quickAmountChip: {
    minHeight: 16,
    minWidth: 34,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#7B797E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickAmountText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '700',
  },
  textField: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  recipientPillsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
    marginBottom: 2,
  },
  recipientChip: {
    minHeight: 16,
    minWidth: 36,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#848187',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipientChipText: {
    color: '#F8F5FB',
    fontSize: 8,
    fontWeight: '700',
  },
  sendButton: {
    minHeight: 34,
    borderRadius: 999,
    backgroundColor: '#808080',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  sendButtonText: {
    color: '#F9F7FA',
    fontSize: 10,
    fontWeight: '700',
  },
  bottomNav: {
    height: 60,
    borderRadius: 16,
    backgroundColor: '#2C262E',
    borderWidth: 1,
    borderColor: '#675C6A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    flex: 1,
  },
  tabIcon: {
    width: 22,
    height: 18,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#D9D0DC',
    opacity: 0.95,
  },
  tabIconActive: {
    borderColor: '#D18DD9',
  },
  tabLabel: {
    color: '#D7D1DA',
    fontSize: 9,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#D98ED5',
  },
});
