import { StyleSheet } from 'react-native';

export const scannerStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#0A090B',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
  },
  topGlow: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 230,
    backgroundColor: 'rgba(147, 76, 255, 0.18)',
    top: 42,
    right: -84,
  },
  bottomGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(120, 60, 190, 0.16)',
    bottom: 12,
    left: -80,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 52,
    left: -120,
    width: 460,
    height: 460,
    opacity: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIcon: {
    color: '#F4EEF9',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '400',
  },
  avatarMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#EBEBEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    color: '#2B2430',
    fontSize: 13,
    fontWeight: '700',
  },
  titleWrap: {
    alignItems: 'center',
    marginBottom: 12,
  },
  titleIcon: {
    width: 28,
    height: 28,
    marginBottom: 6,
  },
  title: {
    color: '#B5A9FF',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.68)',
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '500',
    marginTop: 4,
  },
  scanFrameOuter: {
    width: '100%',
    aspectRatio: 0.82,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#67607A',
    backgroundColor: '#292629',
    overflow: 'hidden',
    alignSelf: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  camera: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2A272C',
  },
  cameraFallbackText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  scanCorners: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  corner: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderColor: '#FFFFFF',
    borderWidth: 0,
  },
  cornerTopLeft: {
    top: 8,
    left: 8,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 18,
  },
  cornerTopRight: {
    top: 8,
    right: 8,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 18,
  },
  cornerBottomLeft: {
    bottom: 8,
    left: 8,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 18,
  },
  cornerBottomRight: {
    bottom: 8,
    right: 8,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 18,
  },
  scanLine: {
    position: 'absolute',
    left: '10%',
    right: '10%',
    height: 3,
    backgroundColor: '#FFFFFF',
    top: '50%',
    marginTop: -1.5,
    borderRadius: 999,
  },
  resultCard: {
    backgroundColor: '#29262C',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#5E536E',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  resultLabel: {
    color: '#C7B8DD',
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 6,
  },
  resultValue: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  resultButton: {
    marginTop: 10,
    minHeight: 28,
    borderRadius: 999,
    backgroundColor: '#B7AEE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultButtonText: {
    color: '#2A2030',
    fontSize: 10,
    fontWeight: '800',
  },
  permissionCard: {
    backgroundColor: '#29262C',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#5E536E',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  permissionText: {
    color: '#FFFFFF',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '500',
    marginBottom: 10,
  },
  permissionButton: {
    minHeight: 30,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#B7AEE7',
  },
  permissionButtonText: {
    color: '#2A2030',
    fontSize: 10,
    fontWeight: '800',
  },
  galleryButton: {
    alignSelf: 'center',
    minHeight: 30,
    minWidth: 142,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#B7AEE7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  galleryButtonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  bottomNav: {
    height: 60,
    borderRadius: 16,
    backgroundColor: '#2C262E',
    borderWidth: 1,
    borderColor: '#675C6A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    flex: 1,
  },
  tabIcon: {
    width: 22,
    height: 18,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#D9D0DC',
    opacity: 0.95,
  },
  tabIconScanner: {
    borderColor: '#D18DD9',
    backgroundColor: 'rgba(209,141,217,0.15)',
  },
  tabIconActive: {
    borderColor: '#D18DD9',
  },
  tabLabel: {
    color: '#D7D1DA',
    fontSize: 9,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#D98ED5',
  },
});
