import { StyleSheet } from 'react-native';

export const walletStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#080707',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 24,
    minHeight: '100%',
  },
  topGlow: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 230,
    backgroundColor: 'rgba(147, 76, 255, 0.18)',
    top: 42,
    right: -84,
  },
  bottomGlow: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: 'rgba(120, 60, 190, 0.16)',
    bottom: 12,
    left: -80,
  },
  vectorTopLeft: {
    position: 'absolute',
    top: 52,
    left: -120,
    width: 460,
    height: 460,
    opacity: 1,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIcon: {
    color: '#F4EEF9',
    fontSize: 28,
    lineHeight: 28,
    fontWeight: '400',
  },
  avatarMark: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: '#EBEBEB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarLetter: {
    color: '#2B2430',
    fontSize: 13,
    fontWeight: '700',
  },
  greetingBlock: {
    marginBottom: 18,
    paddingLeft: 2,
  },
  greeting: {
    color: 'rgba(255,255,255,0.38)',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '400',
  },
  userName: {
    color: '#E8E0ED',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: -1,
  },
  balanceCard: {
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 18,
    marginBottom: 16,
    minHeight: 102,
  },
  balanceCardContent: {
    position: 'relative',
    zIndex: 2,
  },
  remitTitle: {
    color: 'rgba(244, 233, 255, 0.86)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 10,
    marginLeft: 4,
  },
  totalBalancePanel: {
    backgroundColor: '#312B35',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#67557E',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    minHeight: 64,
  },
  totalBalanceLabel: {
    color: 'rgba(232, 222, 244, 0.52)',
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  totalBalanceValue: {
    color: '#FFFFFF',
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  transferCard: {
    backgroundColor: '#2D2832',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#645778',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 14,
    marginBottom: 18,
  },
  transferCardTitle: {
    color: 'rgba(228, 220, 240, 0.6)',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  transferFieldLabel: {
    color: 'rgba(223, 214, 242, 0.62)',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 4,
    marginBottom: 6,
    letterSpacing: 0.25,
  },
  tokenSelect: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tokenSelectLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tokenSymbol: {
    color: '#F4F1F5',
    fontSize: 10,
    fontWeight: '800',
  },
  tokenBalance: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 8,
    marginTop: 1,
    fontWeight: '600',
  },
  dropdownChevron: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 20,
    lineHeight: 20,
    marginTop: -2,
  },
  assetPickerRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    marginBottom: 8,
  },
  assetChip: {
    minHeight: 18,
    minWidth: 34,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#68666B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetChipActive: {
    backgroundColor: '#8F7AA0',
  },
  assetChipText: {
    color: '#FFFFFF',
    fontSize: 8,
    fontWeight: '800',
  },
  amountBlock: {
    marginBottom: 2,
  },
  amountInput: {
    minHeight: 38,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  quickAmountRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  quickAmountChip: {
    minHeight: 16,
    minWidth: 34,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#7B797E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickAmountText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  textField: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#6C6B71',
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  recipientPillsRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
    marginBottom: 2,
  },
  recipientChip: {
    minHeight: 16,
    minWidth: 36,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: '#848187',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recipientChipText: {
    color: '#F8F5FB',
    fontSize: 8,
    fontWeight: '700',
  },
  sendButton: {
    minHeight: 24,
    borderRadius: 999,
    backgroundColor: '#808080',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  sendButtonText: {
    color: '#F9F7FA',
    fontSize: 9,
    fontWeight: '700',
  },
  cardLabel: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  balanceValue: {
    color: '#FFFFFF',
    fontSize: 40,
    lineHeight: 44,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  balanceDelta: {
    color: '#8AE06E',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 4,
  },
  phpEquivalent: {
    color: 'rgba(255,255,255,0.50)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
    marginBottom: 10,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  actionButtonPrimary: {
    flex: 1,
    minHeight: 28,
    borderRadius: 8,
    backgroundColor: '#4A3E56',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7F698C',
  },
  actionButtonSecondary: {
    flex: 1,
    minHeight: 28,
    borderRadius: 8,
    backgroundColor: '#423647',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7F698C',
  },
  actionButtonText: {
    color: '#D7D0DD',
    fontSize: 13,
    fontWeight: '600',
  },
  insightCard: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 13,
    marginBottom: 16,
    flexDirection: 'row',
    gap: 12,
    minHeight: 108,
    borderRadius: 18,
  },
  insightCardContent: {
    position: 'relative',
    zIndex: 2,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  insightAvatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: '#8A2EF2',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    overflow: 'hidden',
  },
  insightAvatarText: {
    color: '#FFD9FF',
    fontSize: 18,
    lineHeight: 18,
  },
  takaAvatarIcon: {
    width: 48,
    height: 48,
  },
  insightBody: {
    flex: 1,
  },
  insightTitle: {
    color: '#E5D8EE',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 7,
    letterSpacing: 0.3,
  },
  insightText: {
    color: '#D7D0D6',
    fontSize: 9,
    lineHeight: 13,
    fontWeight: '400',
  },
  highlightBlue: {
    color: '#4B8CFF',
    fontWeight: '700',
  },
  highlightOrange: {
    color: '#FF9B63',
    fontWeight: '700',
  },
  chatButton: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'right',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(154, 127, 213, 0.92)',
  },
  chatBotIcon: {
    width: 24,
    height: 24,
  },
  chatButtonText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  assetsCard: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    marginBottom: 24,
    borderRadius: 18,
  },
  assetsCardContent: {
    position: 'relative',
    zIndex: 2,
  },
  assetsTitle: {
    color: '#DCCFE2',
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 12,
    letterSpacing: 0.4,
  },
  assetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  assetIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  assetBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assetBadgeBlue: {
    backgroundColor: '#2087FF',
  },
  assetBadgeTeal: {
    backgroundColor: '#20C5C3',
  },
  assetBadgePurple: {
    backgroundColor: '#7C3AED',
  },
  assetBadgeText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  assetSymbol: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  assetName: {
    color: '#7D7881',
    fontSize: 16,
    marginTop: 1,
    fontWeight: '500',
  },
  assetBalance: {
    color: '#DCD7E2',
    fontSize: 16,
    fontWeight: '700',
  },
  floatingBot: {
    position: 'absolute',
    right: 16,
    bottom: 80,
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingBotIcon: {
    width: 70,
    height: 70,
  },
  notificationDot: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#3CF06B',
  },
  bottomNav: {
    marginHorizontal: 18,
    marginBottom: 8,
    height: 60,
    borderRadius: 16,
    backgroundColor: '#2C262E',
    borderWidth: 1,
    borderColor: '#675C6A',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    flex: 1,
  },
  tabIcon: {
    width: 22,
    height: 18,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#D9D0DC',
    opacity: 0.95,
  },
  tabIconActive: {
    borderColor: '#D18DD9',
  },
  tabIconStrong: {
    borderRadius: 6,
  },
  remitTabIcon: {
    width: 22,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#D9D0DC',
    backgroundColor: '#D18DD9',
  },
  scanTabIcon: {
    width: 22,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#D9D0DC',
    borderStyle: 'dashed',
  },
  historyTabIcon: {
    width: 22,
    height: 18,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#D9D0DC',
  },
  tabLabel: {
    color: '#D7D1DA',
    fontSize: 9,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#D98ED5',
  },
  pressedState: {
    opacity: 0.88,
    transform: [{ scale: 0.99 }],
  },
});